app/routes/auth.py
from flask import Blueprint,render_template,request,redirect,flash,session,url_for
from app import db
from app.models.models import Users,Feedback
from functools import wraps
import re
auth_bp=Blueprint("auth",__name__)

def login_user(user):
    session["username"]=user.username
    session["user_id"]=user.id
    session["loged_in"]=True


def input_validator(username,email,password):
    def validate_username(username):
        if not username:
            return (False, "Username cannot be empty")
        if len(username) < 4 or len(username) > 20:
            return (False, "Username must be 4-20 characters long")
        if not username[0].isalpha():
            return (False, "Username must start with a letter")
        if not re.fullmatch(r'^[A-Za-z0-9_]+$', username):
            return (False, "Username can only contain letters, numbers and underscores")
        if '__' in username:
            return (False, "Username cannot contain consecutive underscores")
        if username.endswith('_'):
            return (False, "Username cannot end with underscore")
        return (True,)


    def validate_email(email):
        if not email:
            return (False, "Email cannot be empty")
        if len(email) > 254:
            return (False, "Email is too long (max 254 chars)")
        pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        
        if not re.fullmatch(pattern, email):
            return (False, "Please enter a valid email address")
        parts = email.split('@')
        if len(parts) != 2:
            return (False, "Email must contain exactly one @")
        
        local_part = parts[0]
        domain_part = parts[1]
        if len(local_part) > 64:
            return (False, "Email local part is too long (max 64 chars)")
        if local_part.startswith('.') or local_part.endswith('.'):
            return (False, "Email local part cannot start or end with dot")
        if '..' in local_part:
            return (False, "Email local part cannot contain consecutive dots")
        if '.' not in domain_part:
            return (False, "Domain must contain a dot")
        if domain_part.startswith('-') or domain_part.endswith('-'):
            return (False, "Domain cannot start or end with hyphen")
        if '..' in domain_part:
            return (False, "Domain cannot contain consecutive dots")
        return (True,)
    

    def validate_password(password):
        if not password:
            return (False,"Password cannot be empty")
        if len(password) < 8:
            return (False,"Password is too short (minimum 8 characters) ")
        if len(password)>12:
            return (False,"Password is too long (maximum 12 characters) ")
        if not re.search(r"[A-Z]", password):
            return (False,"Password must contain a uppercase character")
        if not re.search(r"[a-z]", password):
            return (False,"Password must contain a lowercase character")
        if not re.search(r"[0-9]", password):
            return (False,"Password must contain a digit")
        if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
            return (False,"Password must contain a special character")
        return (True,)
    
    return [validate_username(username),validate_email(email),validate_password(password)]



def logout_user():
    session.clear()

def get_current_user():
    if 'user_id' in session and session.get("loged_in"):
        return Users.query.filter_by(id=session["user_id"])
    return None

def login_required(func):
    @wraps(func)
    def wrapper(*args,**kwargs):
        if 'user_id' not in session or not session["loged_in"]:
            flash('Please log in to access this page','info')
            return redirect(url_for('auth.login'))
        return func(*args,**kwargs)
    return wrapper


@auth_bp.route("/login",methods=["POST","GET"])
def login():
    logout_user()
    if request.method=="POST":
        username=request.form.get("username")
        email=request.form.get("email")
        password=request.form.get("password")
        user=Users.query.filter_by(email=email).first()
        if user and user.username==username and user.check_password(password):
                login_user(user=user)
                flash(f"Welcome {username} !You have successfully loged in","success")
                return redirect(url_for("cont.dashboard"))
        flash('Invalid credentials','error')
    return render_template("login.html")

@auth_bp.route("/register",methods=["POST","GET"])
def register():
    if request.method=="POST":
        username=request.form.get("username")
        email=request.form.get("email")
        password=request.form.get("password")
        user=Users.query.filter_by(email=email).first()
        if user:
            flash("This email address already exists try another email","error")
        else:
            inp_validity=input_validator(username=username,email=email,password=password)
            for valid in inp_validity:
                if not valid[0]:
                    flash(valid[1],"error")
                    return redirect(url_for("auth.register"))
            
            new_user=Users(username=username,email=email)
            new_user.set_password(password=password)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for("auth.success"))

    return render_template("register.html")

@auth_bp.route("/success")
def success():
    logout_user()
    return render_template("success.html")

@auth_bp.route("/feedback",methods=["POST"])
def feedback():
    got_user=True
    username=session.get("username")
    feedback=request.form.get('feedback')
    star=request.form.get('star')
    try:
        star=int(star)
    except:
        pass
    if not username:
        username="Unknown User"
        got_user=False
    
    if username and feedback:
        new_feedback=Feedback(username=username,feedback=feedback,star=star)
        db.session.add(new_feedback)
        db.session.commit()
        if got_user:
            flash(f"Thanks {username} for your feedback","success")
        else:
            flash("Thanks Sir for your feedback","success")
        
        return redirect(url_for("cont.dashboard"))
    
@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have successfully loged out","info")
    return redirect(url_for("auth.login"))
           
    


    

app/routes/content.py
from flask import Blueprint,render_template,request,redirect,flash,session,url_for
from app.models.models import Users,Category,Budget,Expanse
from functools import wraps
from app import db
from datetime import datetime,date,timedelta

cont_bp=Blueprint('cont',__name__)

def login_required(func):
    @wraps(func)
    def wrapper(*args,**kwargs):
        if 'user_id' not in session or not session["loged_in"]:
            flash('Please log in to access our website','info')
            return redirect(url_for('auth.login'))
        return func(*args,**kwargs)
    return wrapper
def get_current_user():
    if 'user_id' in session and session.get("loged_in"):
        return Users.query.filter_by(id=session["user_id"])
    return None

def create_budget(category_id,amount,period):
    user_id=session.get("user_id")
    period=period.lower()
    today=date.today()
    start_date=today
    if period=="monthly":
        end_date=(today.replace(day=1)+timedelta(days=32))
        end_date=end_date.replace(day=1)-timedelta(days=1)
    elif period=="weekly":
        end_date=today+timedelta(days=7)
    else:
        end_date=today.replace(year=today.year+1)
    budget=Budget(amount=amount,period=period,start_date=start_date,end_date=end_date,user_id=user_id,category_id=category_id)
    db.session.add(budget)
    db.session.commit() 

def get_budget_status(category_id):
    user_id=session.get("user_id")
    today=date.today()
    budget=Budget.query.filter(
            Budget.user_id==user_id,
            Budget.category_id==category_id,
            Budget.start_date<=today,
            (Budget.end_date>=today) | (Budget.end_date==None)).first()
    if not budget:
        return None
    expenses=Expanse.query.filter(
        Expanse.user_id==user_id,
        Expanse.Category_id==category_id,
        Expanse.date>=budget.start_date,
        Expanse.date<=(budget.end_date if budget.end_date else today)
    ).all()
    total_spent=sum(expense.amount for expense in expenses )
    remaining=budget.amount-total_spent
    category=Category.query.filter_by(id=category_id).one()
    category_name=category.name
    remaining_days=budget.end_date-today
    if budget.amount > 0:
        percentage_used = min((total_spent / budget.amount) * 100, 100)
    else:
        percentage_used = 0

    is_active="active" if remaining>=0 else "deactive"
    return {
        'budget':budget,
        'category_name':category_name,
        'total_spent':total_spent,
        'remaining':remaining,
        'percentage_used':percentage_used,
        'period_start':budget.start_date,
        'period_end':budget.end_date,
        'remaining_days':remaining_days,
        "is_active":is_active
    }
@cont_bp.route("/")
@login_required
def dashboard():
   
    all_categories=Category.query.filter_by(user_id=session["user_id"]).all()
    return render_template("home.html",categories=all_categories)

@cont_bp.route("/budget")
@login_required
def budget():
    categories=Category.query.filter_by(user_id=session.get("user_id")).all()
    budgets=[]
    for category in categories:
        budToAdd=get_budget_status(category.id)
        if budToAdd:
            budgets.append(budToAdd)
    return render_template("budget.html",categories=categories,budgets=budgets)
@cont_bp.route("/help")
@login_required
def help():
    return render_template("help.html")

@cont_bp.route("/add_category",methods=["POST"])
@login_required
def add_category():
        name=request.form.get('category_name')
        description=request.form.get("description")
        exist_cate=Category.query.filter_by(user_id=session["user_id"],name=name).all()
        if exist_cate:
            flash("This Category already exists in your Categories list try another name","error")
            return redirect(url_for("cont.dashboard"))
        new_category=Category(name=name,description=description,user_id=session["user_id"])
        db.session.add(new_category)
        db.session.commit()
        flash("New category added","info")
        return redirect(url_for("cont.dashboard"))

@cont_bp.route("/category/<int:cate_id>")
@login_required
def go_to_category(cate_id):
    if not session.get("date"):
         session["date"]=datetime.date(datetime.today())
    category=Category.query.filter_by(id=cate_id).one()
    session["category"]=cate_id
    expanses=Expanse.query.filter_by(Category_id=cate_id,date=session["date"]).all()
    return render_template("category.html",category=category,expenses=expanses)

@cont_bp.route("/sort_date",methods=["POST"])
@login_required
def sort_date():
    date=request.form.get("date")
    session["date"]=date
    return redirect(url_for('cont.go_to_category',cate_id=session["category"]))

@cont_bp.route("/add_expanse",methods=["POST"])
@login_required
def add_expanse():
    amount=request.form.get('amount')
    title=request.form.get('title')
    pay_method=request.form.get('pay_method')
    location=request.form.get('location')
    receipt_filename=request.form.get('receipt_filename')
    category_id=request.form.get('category_id')
    new_expense=Expanse(amount=amount,title=title,payment_method=pay_method,location=location,
                        receipt_filename=receipt_filename,Category_id=category_id ,user_id=session.get("user_id"))
    db.session.add(new_expense)
    db.session.commit()
    flash(f"New Expanse amount {amount} added ","info")
    return redirect(url_for("cont.go_to_category",cate_id=category_id))

@cont_bp.route("/delete_exp/<int:exp_id>",methods=["POST"])
@login_required
def delete_exp(exp_id):
    expense=Expanse.query.get(exp_id)
    db.session.delete(expense)
    db.session.commit()
    return redirect(url_for("cont.go_to_category",cate_id=session.get("category")))

@cont_bp.route("/edit_exp/<int:exp_id>",methods=["GET","POST"])
@login_required
def edit_exp(exp_id):
    if request.method=="POST":
        expense=Expanse.query.get(exp_id)
        amount=request.form.get('amount')
        title=request.form.get('title')
        pay_method=request.form.get('pay_method') 
        location=request.form.get('location')
        receipt_filename=request.form.get('receipt_filename')  
        category_id=request.form.get('category_id')
        expense.category_id=category_id
        expense.payment_method=pay_method
        expense.date=date.today()
        if amount:
            expense.amount=amount
        if title :
            expense.title=title
        if location:
            expense.location=location
        if receipt_filename:
            expense.receipt_filename=receipt_filename
        db.session.commit()
        flash("Expanse Updated","info")
        return redirect(url_for("cont.go_to_category",cate_id=session.get("category")))
   
    categories=Category.query.filter_by(user_id=session.get("user_id"))
    return render_template("edit_expanses.html",categories=categories)



@cont_bp.route("/addBudget",methods=["POST"])
@login_required
def add_budget():
    amount=request.form.get("amount")
    period=request.form.get("period")
    category_id=request.form.get("category_id")
    create_budget(category_id=category_id,amount=amount,period=period)
    return redirect(url_for('cont.budget'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Expanse Tracker{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/footer.css') }}">
</head>
<body>
    <header>
       <nav>
        <h1>ExTrack</h1>
        <div class="nav-btns">
            <ul>
                <li>
                    <a href="{{ url_for('cont.dashboard') }}">
                        <div class="nav-btn">Home</div>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('cont.budget') }}">
                        <div class="nav-btn">Budget</div>
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('cont.help') }}">
                        <div class="nav-btn">Help</div>
                    </a>
                </li>
            </ul>
            <form action="{{ url_for('auth.logout') }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="submit" value="Logout" class="logout-btn">
            </form>

        </div>
       </nav> 

       <div class="status-bar">
        {% with messages=get_flashed_messages(with_categories=True) %}
        {% for cate,msg in messages %}
        <p class="{{cate|lower}} flashed-msg">{{msg}}</p>
        {% endfor %}
        {% endwith %}
    </div>
    </header>
    <main>
        
        {% block content %}{% endblock %}
    </main>
    <footer>
        <div class="feedback-board">
            <div class="fb-title">Leave a Review</div>            
            <form action="{{ url_for('auth.feedback') }}"method="POST" class="feedback-from"> 
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="star-rating">
                    {% for i in range(5,0,-1) %}
                    <input type="radio" name="star" id="star-{{ i }}" value= "{{i}}">
                    <label for="star-{{ i }}">&#9733</label>
                    {% endfor %}
                </div>
                <textarea name="feedback" class="long-txt" placeholder="Your Feedback" required maxlength="500"></textarea>
                <input type="submit" value="Send Feedback" class="feedback-btn">
            </form>
        </div>
        
        <span class="acknoledgement">@2025 made by rikan maji</span>
    </footer>
    <script src="{{ url_for('static',filename='js/script.js') }}" ></script>
</body>
</html>

app/templates/base_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ExTrack{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static' , filename='css/auth_style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/footer.css') }}">
</head>
<body>
    <header>
        <div class="hero-sec">
            <div class="hero-title">
                <h1>ExTrack</h1>
                <h3>Track Your Daily Expanses With ExTrack</h3>
            </div>

            
        </div>
        <div class="statusbar">
            {% with messages=get_flashed_messages(with_categories=True) %}
            {% for cate,msg in messages %}
            <p class="{{cate|lower}} flashed-msg">{{msg}}</p>
            {% endfor %}
            {% endwith %}
        </div>
    </header>
    <main>
        {% block content %} {% endblock %}
    </main>
    <footer>
        {% block auth_footer %}
        <div class="feedback-board">
            <div class="fb-title">Leave a Review</div>            
            <form action="{{ url_for('auth.feedback') }}"method="POST" class="feedback-from"> 
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="star-rating">
                    {% for i in range(5,0,-1) %}
                    <input type="radio" name="star" id="star-{{ i }}" value= "{{i}}">
                    <label for="star-{{ i }}">&#9733</label>
                    {% endfor %}
                </div>
                <textarea name="feedback" class="long-txt" placeholder="Your Feedback" required></textarea>s
                <input type="submit" value="Send Feedback" class="feedback-btn">
            </form>
        </div>
        
        <span class="acknoledgement">@2025 made by rikan maji</span>
        {% endblock %}
        
    </footer>

</body>
</html>

app/templates/budget.html
{% extends 'base.html' %}
{% block title %}Budgets{% endblock %}
{% block content %}
<h1 class="pageTitle"> Create Budgets </h1>
<div class="inpBarTitle">Track your Expanses! Compare your targeted Budget</div> 

<form action="{{ url_for('cont.add_budget') }}" method="POST" class="inpSec">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="inpBarTitle">Add New Budget</div>
    <div class="inpContainer">
        <input type="number" name="amount" required placeholder="Amount" class="add-inp alignFlexEnd">
        <div class="select-box">
            <label for="pay_method">Period</label>
            <select name="period" id="pay_method" class="add-inp">
                <option value="yearly">Yearly</option>
                <option value="monthly">Monthy</option>
                <option value="weekly">Weekly</option>
            </select>
        </div>
        <div class="select-box">
            <label for="category_name">Category</label>
            <select name="category_id" id="category_name" required class="add-inp">   
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <input type="submit" value="+Add" class="add-btn">
</form>
{% if budgets %}
<div class="container">
{% for budget in budgets %}
<div class="budget gls-efct">
    <span>Budget Category : {{ budget['category_name'] }}</span>
    <span>Budget Start : {{ budget['period_start'] }}</span>
    <span>Budget End : {{ budget['period_end'] }}</span>
    <span>Budget Amount : {{ budget['budget'].amount }}</span>
    <span>Total Spent : {{ budget['total_spent'] }}</span>
    <span class="{{ budget['is_active'] }}">Remaining Amount: {{ budget['remaining'] }}</span>
    <span>Remaining Days: {{ budget['remaining_days'] }}</span>
    <span>Percentage Used : {{ budget['percentage_used'] }}%</span>
    <div class="budBar">
        <div class="budBarPer" style="width: {{ budget['percentage_used'] }}%;"></div>
    </div>
    
</div>
{% endfor %}
</div>
{% endif %}

{% endblock %}

app/templates/category.html
{% extends 'base.html' %}
{% block title %}Category{% endblock %}
{% block content %}
<h1 class="pageTitle"> {{ category.name }} </h1>
<div class="description">
    <div class="inpBarTitle">Description</div> 
    <p>{{ category.description }}</p>
</div>

<form action="{{ url_for('cont.add_expanse') }}" method="POST" class="inpSec">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="inpBarTitle">Add New Expanse</div>
    <div class="inpContainer">
        <input type="number" name="amount" required placeholder="Amount" class="add-inp alignFlexEnd">
        <div class="select-box">
            <label for="pay_method">Payment Method</label>
            <select name="pay_method" id="pay_method" class="add-inp add-inp-slct">
                <option value="Credit Card">Credit Card</option>
                <option value="Debit Card">Debit Card</option>
                <option value="Bank Transfer">Bank Transfer</option>
                <option value="Mobile Payment">Mobile Payment</option>
                <option value="Cash">Cash</option>
            </select>
        </div>
        <input type="text" name="location" maxlength="100" placeholder="Location" class="add-inp alignFlexEnd">
        
    </div>
    <div class="inpContainer">            
        <input type="text" name="title" required maxlength="50" placeholder="Title" class="add-inp alignFlexEnd">
        <div class="select-box">
            <label for="category_name">Category</label>
            <select name="category_id" id="category_name" required class="add-inp add-inp-slct">   
                <option value="{{ category.id }}">{{ category.name }}</option>
            </select>
        </div>
        <input type="text" name="receipt_filename" maxlength="100" placeholder="Receipt Filename" class="add-inp alignFlexEnd">
    </div> 
    <div class="addBtn-sec">
        <input type="submit" value="+Add" class="add-btn">
    </div>        
    
</form>

<div class="container">
    <form action="{{ url_for('cont.sort_date') }}" method="POST" class="sort-exp">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input type="date" name="date">
        <input type="submit" value="Sort">
    </form>
    {% if expenses %}  
    <div class="show-exp">
        <div class="exp-heading">
            <div class="exp-rows">
                <div class="expBox exp-title expHead">Title</div>
                <div class="expBox exp-amount expHead">Amount</div>
                <div class="expBox exp-date expHead">Date</div>
                <div class="expBox exp-details expHead">Show Deatils</div>
            </div>
        </div>
        <div class="exp-content">
            {% for expanse in expenses %}
            <div class="exp-rows">
                <div class="expBox exp-title">{{ expanse.title }}</div>
                <div class="expBox exp-amount">{{ expanse.amount }}</div>
                <div class="expBox exp-date">{{ expanse.date }}</div>
                <div class="expBox exp-details"><button class="dropbtn" onclick="dropDownShow('dropContent-{{ expanse.id }}')"> Details > </button></div>
            </div>
                <div class="dropContent" id="dropContent-{{ expanse.id }}">
                    <div>Created on : {{ expanse.created_on }}</div>
                    <div>Updated on : {{ expanse.updated_on }}</div>
                    <div>Payment Method : {{ expanse.payment_method }}</div>
                    <div>Location : {{ expanse.location }}</div>
                    <div>Receipt Filename : {{ expanse.receipt_filename }}</div> 
                    <div class="btn-section">
                        <form action="{{ url_for('cont.edit_exp',exp_id=expanse.id) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" value="Edit" class="dropEdit dropedBtn">
                        </form>
                        <form action="{{ url_for('cont.delete_exp',exp_id=expanse.id) }}" method="POST">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input type="submit" value="Delete" class="dropDel dropedBtn">
                        </form>
                        <input type="submit" value="Close" onclick="dropDownShow('dropContent-{{ expanse.id }}')" class="dropClose dropedBtn">
                    </div>
                    
                </div>
            
            {% endfor %}
        </div>
    </div>
 
</div>       
{% endif %}      
{% endblock %}

app/templates/edit_expanses.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" class="inpSec">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="inpBarTitle">Edit Expanse</div>
    <div class="inpContainer">
        <input type="number" name="amount" placeholder="Amount" class="add-inp alignFlexEnd">
        <div class="select-box">
            <label for="pay_method">Payment Method</label>
            <select name="pay_method" id="pay_method" class="add-inp">s
                <option value="Credit Card">Credit Card</option>
                <option value="Debit Card">Debit Card</option>
                <option value="Bank Transfer">Bank Transfer</option>
                <option value="Mobile Payment">Mobile Payment</option>
                <option value="Cash">Cash</option>
            </select>
        </div>
        <input type="text" name="location" maxlength="100" placeholder="Location" class="add-inp alignFlexEnd">
        
    </div>
    <div class="inpContainer">            
        <input type="text" name="title" maxlength="50" placeholder="Title" class="add-inp alignFlexEnd">
        <div class="select-box">
            <label for="category_name">Category</label>
            <select name="category_id" id="category_name" class="add-inp">   
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <input type="text" name="receipt_filename" maxlength="100" placeholder="Receipt Filename" class="add-inp alignFlexEnd">
    </div>         
    <input type="submit" value="Done" class="add-btn">
</form>
{% endblock %}

app/templates/help.html
{% extends 'base.html' %}
{% block title %}Help{% endblock %}
{% block content %}
<h1 class="pageTitle"> Help Section </h1>
<h3 class="inpBarTitle">How everything works?</h3>
    <p class="helpDes">So here you will find how to work with every options. Here you will able to know about the features of this website</p>
<div class="helpContainer">
<h3>What should be our workflow in Extrack?</h3>
<ol>
    <li>First create some categories according to your need (e.g,Online Purchase Expanses,House Bill)</li>
    <li>Then if you want to take a target go to budget and set a expanse target</li>
    <li>Go to any category and add your every day's expenses of that category</li>
</ol>
<h3>What is budget?</h3>
<p>Through creating budgets you can set a target of expanses. You can take weekly,monthly or yearly expanses target on any perticular category.
<h3>Add Category</h3>
<p>After you loged in to this website you have to creates some categories of expanses. You can find the Add category section inside home page.
    You can add categories according to your need</p>
</p>
<h3>Registeration & Login</h3>
<ol>
    <li>Click on register</li>
    <li>Register yourself with your details</li>
    <li>Go to login page and fill up the same details</li>
</ol>

<h3>How to create Category?</h3>
<ol>
    <li>Go to home page then add category section in the top</li>
    <li>Enter your category name</li>
    <li>Enter any description about that category or leave it empty</li>
    <li>Press "+Add" button</li>
</ol>
<p>Note : you can't create category with same name. Category names must be unique</p>

<h3>How to enter a category?</h3>
<ol>
    <li>Create categories</li>
    <li>Go to Categories section inside home page</li>
    <li>Find category according to your need</li>
    <li>Press "GoTo >" button to enter that category</li>
</ol>
<h3>How to add expanses?</h3>
<ol>
    <li>Enter a category</li>
    <li>Go to add new expanse section</li>
    <li>Fill details</li>
    <li>Press "+Add" button</li>
</ol>
<h3>How to filter expanses according to date?</h3>
<ol>
    <li>Chose a date</li>
    <li>Press "Sort" button</li>
</ol>
<p>To see details/Edit expanse/Delete Expanse : Press "Details>" button</p>
<h3>How to create budgets?</h3>
<ol>
    <li>Go to budget page</li>
    <li>Go to the top section(Add New Budget)</li>
    <li>Fill details</li>
    <li>Press "+Add" button</li>
</ol>
<h3>Feedbacks</h3>
<p>Below every page you will find a feedback form. If you want you can send us feedbacks using that form.Just fill up the form and press send</p>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block title %}Home page{% endblock %}
{% block content %}
<div class="add-category gls-efct">
    
    <form action="{{ url_for('cont.add_category') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <div class="inp-sec-div">
            <input type="text" name="category_name" placeholder="Enter Category Name" class="add-inp" required maxlength="64">
            <div class="inpBarTitle">Add New Category</div>
            <input type="submit" value="+Add" class="add-btn">
        </div>
        <textarea name="description" placeholder="Description" id="category-des" maxlength="200"></textarea>
        
    </form>
</div>
{% if categories %}
<div class="container">
    <span class="plain-text">Categories</span>
    <div class="cate-frame">
        <input type="button" value="<" class="gls-efct slide-btn" onclick="goPrev()">
        <div class="display-cate ">
        {% for category in categories %}
        <div class="category  cate-{{ category.id%4 }}">
            <h4>{{ category.name }}</h4>
            <p>{{ category.description }}</p>
            <form action="{{ url_for('cont.go_to_category' , cate_id=category.id)}}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="submit" value="GoTo >" class="gls-efct">
            </form>
        </div>
        {% endfor %}
        </div>
        <input type="button" value=">" class="gls-efct slide-btn" onclick="goNext()">
    </div>
</div>
{% endif %}


{% endblock %}

app/templates/login.html
{% extends "base_auth.html" %}

{% block title %}Login{% endblock %}


{% block content %}
<div class="auth-des gls-efct">
<div class="auth-title">Login</div>
<form method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <input type="text" placeholder="Username" name="username" class="form-inp gls-efct" maxlength="64">
    <input type="text" placeholder="Email" name="email" class="form-inp gls-efct" maxlength="120">
    <input type="text" placeholder="Password" name="password" class="form-inp gls-efct">
    <input type="submit" value="Login" class="form-but gls-efct">

</form>
<a href="{{ url_for('auth.register') }}">Register</a>
</div>
{% endblock %}